import Common   # The code to test

def test_idToColumnName_Eith_Max_8():
  assert Common.idToColumnName(1, 8) == 'a'
  assert Common.idToColumnName(2, 8) == 'b'
  assert Common.idToColumnName(3, 8) == 'c'
  assert Common.idToColumnName(4, 8) == 'd'
  assert Common.idToColumnName(5, 8) == 'e'
  assert Common.idToColumnName(6, 8) == 'f'
  assert Common.idToColumnName(7, 8) == 'g'
  assert Common.idToColumnName(8, 8) == 'h'
  assert Common.idToColumnName(9, 8) == 'a'
  assert Common.idToColumnName(10, 8) == 'b'
  assert Common.idToColumnName(11, 8) == 'c'
  assert Common.idToColumnName(12, 8) == 'd'
  assert Common.idToColumnName(13, 8) == 'e'
  assert Common.idToColumnName(14, 8) == 'f'
  assert Common.idToColumnName(15, 8) == 'g'
  assert Common.idToColumnName(16, 8) == 'h'
  assert Common.idToColumnName(17, 8) == 'a'
  assert Common.idToColumnName(18, 8) == 'b'
  assert Common.idToColumnName(19, 8) == 'c'
  assert Common.idToColumnName(20, 8) == 'd'
  assert Common.idToColumnName(21, 8) == 'e'
  assert Common.idToColumnName(22, 8) == 'f'
  assert Common.idToColumnName(23, 8) == 'g'
  assert Common.idToColumnName(24, 8) == 'h'
  assert Common.idToColumnName(25, 8) == 'a'
  assert Common.idToColumnName(26, 8) == 'b'
  assert Common.idToColumnName(27, 8) == 'c'
  assert Common.idToColumnName(28, 8) == 'd'
  assert Common.idToColumnName(29, 8) == 'e'
  assert Common.idToColumnName(30, 8) == 'f'
  assert Common.idToColumnName(31, 8) == 'g'
  assert Common.idToColumnName(32, 8) == 'h'
  assert Common.idToColumnName(33, 8) == 'a'
  assert Common.idToColumnName(34, 8) == 'b'
  assert Common.idToColumnName(35, 8) == 'c'
  assert Common.idToColumnName(36, 8) == 'd'
  assert Common.idToColumnName(37, 8) == 'e'
  assert Common.idToColumnName(38, 8) == 'f'
  assert Common.idToColumnName(39, 8) == 'g'
  assert Common.idToColumnName(40, 8) == 'h'
  assert Common.idToColumnName(41, 8) == 'a'
  assert Common.idToColumnName(42, 8) == 'b'
  assert Common.idToColumnName(43, 8) == 'c'
  assert Common.idToColumnName(44, 8) == 'd'
  assert Common.idToColumnName(45, 8) == 'e'
  assert Common.idToColumnName(46, 8) == 'f'
  assert Common.idToColumnName(47, 8) == 'g'
  assert Common.idToColumnName(48, 8) == 'h'
  assert Common.idToColumnName(49, 8) == 'a'
  assert Common.idToColumnName(50, 8) == 'b'
  assert Common.idToColumnName(51, 8) == 'c'
  assert Common.idToColumnName(52, 8) == 'd'
  assert Common.idToColumnName(53, 8) == 'e'
  assert Common.idToColumnName(54, 8) == 'f'
  assert Common.idToColumnName(55, 8) == 'g'
  assert Common.idToColumnName(56, 8) == 'h'
  assert Common.idToColumnName(57, 8) == 'a'
  assert Common.idToColumnName(58, 8) == 'b'
  assert Common.idToColumnName(59, 8) == 'c'
  assert Common.idToColumnName(60, 8) == 'd'
  assert Common.idToColumnName(61, 8) == 'e'
  assert Common.idToColumnName(62, 8) == 'f'
  assert Common.idToColumnName(63, 8) == 'g'
  assert Common.idToColumnName(64, 8) == 'h'

def test_idToColumnName_Eith_Max_X():
  assert Common.idToColumnName(1, 1) == 'a'
  assert Common.idToColumnName(1, 2) == 'a'
  assert Common.idToColumnName(1, 3) == 'a'
  assert Common.idToColumnName(1, 4) == 'a'
  assert Common.idToColumnName(2, 5) == 'b'
  assert Common.idToColumnName(3, 6) == 'c'
  assert Common.idToColumnName(4, 7) == 'd'
  assert Common.idToColumnName(5, 8) == 'e'
  assert Common.idToColumnName(6, 9) == 'f'
  assert Common.idToColumnName(7, 10) == 'g'
  assert Common.idToColumnName(8, 30) == 'h'
  assert Common.idToColumnName(9, 60) == 'i'
  assert Common.idToColumnName(10, 90) == 'j'

  
def test_idToColumnName_Max_X():
  assert Common.idToColumnName(1, 30) == 'a'
  assert Common.idToColumnName(27, 30) == 'aa'
  assert Common.idToColumnName(30, 30) == 'dd'
  assert Common.idToColumnName(100, 30) == 'j'
  
  
def test_idToLineNumber():  
  assert Common.idToLineNumber(1, 8) == 1
  assert Common.idToLineNumber(2, 8) == 1 
  assert Common.idToLineNumber(3, 8) == 1 
  assert Common.idToLineNumber(4, 8) == 1 
  assert Common.idToLineNumber(5, 8) == 1 
  assert Common.idToLineNumber(6, 8) == 1 
  assert Common.idToLineNumber(7, 8) == 1 
  assert Common.idToLineNumber(8, 8) == 1 
  assert Common.idToLineNumber(9, 8) == 2 
  assert Common.idToLineNumber(10, 8) == 2
  assert Common.idToLineNumber(11, 8) == 2
  assert Common.idToLineNumber(12, 8) == 2
  assert Common.idToLineNumber(13, 8) == 2
  assert Common.idToLineNumber(14, 8) == 2
  assert Common.idToLineNumber(15, 8) == 2
  assert Common.idToLineNumber(16, 8) == 2
  assert Common.idToLineNumber(17, 8) == 3
  assert Common.idToLineNumber(18, 8) == 3
  assert Common.idToLineNumber(19, 8) == 3
  assert Common.idToLineNumber(20, 8) == 3
  assert Common.idToLineNumber(21, 8) == 3
  assert Common.idToLineNumber(22, 8) == 3
  assert Common.idToLineNumber(23, 8) == 3
  assert Common.idToLineNumber(24, 8) == 3
  assert Common.idToLineNumber(25, 8) == 4
  assert Common.idToLineNumber(26, 8) == 4
  assert Common.idToLineNumber(27, 8) == 4
  assert Common.idToLineNumber(28, 8) == 4
  assert Common.idToLineNumber(29, 8) == 4
  assert Common.idToLineNumber(30, 8) == 4
  assert Common.idToLineNumber(31, 8) == 4
  assert Common.idToLineNumber(32, 8) == 4
  assert Common.idToLineNumber(33, 8) == 5
  assert Common.idToLineNumber(34, 8) == 5
  assert Common.idToLineNumber(35, 8) == 5
  assert Common.idToLineNumber(36, 8) == 5
  assert Common.idToLineNumber(37, 8) == 5
  assert Common.idToLineNumber(38, 8) == 5
  assert Common.idToLineNumber(39, 8) == 5
  assert Common.idToLineNumber(40, 8) == 5
  assert Common.idToLineNumber(41, 8) == 6
  assert Common.idToLineNumber(42, 8) == 6
  assert Common.idToLineNumber(43, 8) == 6
  assert Common.idToLineNumber(44, 8) == 6
  assert Common.idToLineNumber(45, 8) == 6
  assert Common.idToLineNumber(46, 8) == 6
  assert Common.idToLineNumber(47, 8) == 6
  assert Common.idToLineNumber(48, 8) == 6
  assert Common.idToLineNumber(49, 8) == 7
  assert Common.idToLineNumber(50, 8) == 7
  assert Common.idToLineNumber(51, 8) == 7
  assert Common.idToLineNumber(52, 8) == 7
  assert Common.idToLineNumber(53, 8) == 7
  assert Common.idToLineNumber(54, 8) == 7
  assert Common.idToLineNumber(55, 8) == 7
  assert Common.idToLineNumber(56, 8) == 7
  assert Common.idToLineNumber(57, 8) == 8
  assert Common.idToLineNumber(58, 8) == 8
  assert Common.idToLineNumber(59, 8) == 8
  assert Common.idToLineNumber(60, 8) == 8
  assert Common.idToLineNumber(61, 8) == 8
  assert Common.idToLineNumber(62, 8) == 8
  assert Common.idToLineNumber(63, 8) == 8
  assert Common.idToLineNumber(64, 8) == 8