import Common   # The code to test

def test_numberToColumnName_Eith_Max_8():
  assert Common.numberToColumnName(1, 8) == 'a'
  assert Common.numberToColumnName(2, 8) == 'b'
  assert Common.numberToColumnName(3, 8) == 'c'
  assert Common.numberToColumnName(4, 8) == 'd'
  assert Common.numberToColumnName(5, 8) == 'e'
  assert Common.numberToColumnName(6, 8) == 'f'
  assert Common.numberToColumnName(7, 8) == 'g'
  assert Common.numberToColumnName(8, 8) == 'h'
  assert Common.numberToColumnName(9, 8) == 'a'
  assert Common.numberToColumnName(10, 8) == 'b'
  assert Common.numberToColumnName(11, 8) == 'c'
  assert Common.numberToColumnName(12, 8) == 'd'
  assert Common.numberToColumnName(13, 8) == 'e'
  assert Common.numberToColumnName(14, 8) == 'f'
  assert Common.numberToColumnName(15, 8) == 'g'
  assert Common.numberToColumnName(16, 8) == 'h'
  assert Common.numberToColumnName(17, 8) == 'a'
  assert Common.numberToColumnName(18, 8) == 'b'
  assert Common.numberToColumnName(19, 8) == 'c'
  assert Common.numberToColumnName(20, 8) == 'd'
  assert Common.numberToColumnName(21, 8) == 'e'
  assert Common.numberToColumnName(22, 8) == 'f'
  assert Common.numberToColumnName(23, 8) == 'g'
  assert Common.numberToColumnName(24, 8) == 'h'
  assert Common.numberToColumnName(25, 8) == 'a'
  assert Common.numberToColumnName(26, 8) == 'b'
  assert Common.numberToColumnName(27, 8) == 'c'
  assert Common.numberToColumnName(28, 8) == 'd'
  assert Common.numberToColumnName(29, 8) == 'e'
  assert Common.numberToColumnName(30, 8) == 'f'
  assert Common.numberToColumnName(31, 8) == 'g'
  assert Common.numberToColumnName(32, 8) == 'h'
  assert Common.numberToColumnName(33, 8) == 'a'
  assert Common.numberToColumnName(34, 8) == 'b'
  assert Common.numberToColumnName(35, 8) == 'c'
  assert Common.numberToColumnName(36, 8) == 'd'
  assert Common.numberToColumnName(37, 8) == 'e'
  assert Common.numberToColumnName(38, 8) == 'f'
  assert Common.numberToColumnName(39, 8) == 'g'
  assert Common.numberToColumnName(40, 8) == 'h'
  assert Common.numberToColumnName(41, 8) == 'a'
  assert Common.numberToColumnName(42, 8) == 'b'
  assert Common.numberToColumnName(43, 8) == 'c'
  assert Common.numberToColumnName(44, 8) == 'd'
  assert Common.numberToColumnName(45, 8) == 'e'
  assert Common.numberToColumnName(46, 8) == 'f'
  assert Common.numberToColumnName(47, 8) == 'g'
  assert Common.numberToColumnName(48, 8) == 'h'
  assert Common.numberToColumnName(49, 8) == 'a'
  assert Common.numberToColumnName(50, 8) == 'b'
  assert Common.numberToColumnName(51, 8) == 'c'
  assert Common.numberToColumnName(52, 8) == 'd'
  assert Common.numberToColumnName(53, 8) == 'e'
  assert Common.numberToColumnName(54, 8) == 'f'
  assert Common.numberToColumnName(55, 8) == 'g'
  assert Common.numberToColumnName(56, 8) == 'h'
  assert Common.numberToColumnName(57, 8) == 'a'
  assert Common.numberToColumnName(58, 8) == 'b'
  assert Common.numberToColumnName(59, 8) == 'c'
  assert Common.numberToColumnName(60, 8) == 'd'
  assert Common.numberToColumnName(61, 8) == 'e'
  assert Common.numberToColumnName(62, 8) == 'f'
  assert Common.numberToColumnName(63, 8) == 'g'
  assert Common.numberToColumnName(64, 8) == 'h'

def test_numberToColumnName_Eith_Max_X():
  assert Common.numberToColumnName(1, 1) == 'a'
  assert Common.numberToColumnName(1, 2) == 'a'
  assert Common.numberToColumnName(1, 3) == 'a'
  assert Common.numberToColumnName(1, 4) == 'a'
  assert Common.numberToColumnName(2, 5) == 'b'
  assert Common.numberToColumnName(3, 6) == 'c'
  assert Common.numberToColumnName(4, 7) == 'd'
  assert Common.numberToColumnName(5, 8) == 'e'
  assert Common.numberToColumnName(6, 9) == 'f'
  assert Common.numberToColumnName(7, 10) == 'g'
  assert Common.numberToColumnName(8, 30) == 'hh'
  assert Common.numberToColumnName(9, 60) == 'iii'
  assert Common.numberToColumnName(10, 90) == 'jjjj'
  
  
def test_numberToLineNumber():
  
  assert Common.numberToLineNumber(1, 8) == 1
  assert Common.numberToLineNumber(2, 8) == 1 
  assert Common.numberToLineNumber(3, 8) == 1 
  assert Common.numberToLineNumber(4, 8) == 1 
  assert Common.numberToLineNumber(5, 8) == 1 
  assert Common.numberToLineNumber(6, 8) == 1 
  assert Common.numberToLineNumber(7, 8) == 1 
  assert Common.numberToLineNumber(8, 8) == 1 
  assert Common.numberToLineNumber(9, 8) == 2 
  assert Common.numberToLineNumber(10, 8) == 2
  assert Common.numberToLineNumber(11, 8) == 2
  assert Common.numberToLineNumber(12, 8) == 2
  assert Common.numberToLineNumber(13, 8) == 2
  assert Common.numberToLineNumber(14, 8) == 2
  assert Common.numberToLineNumber(15, 8) == 2
  assert Common.numberToLineNumber(16, 8) == 2
  assert Common.numberToLineNumber(17, 8) == 3
  assert Common.numberToLineNumber(18, 8) == 3
  assert Common.numberToLineNumber(19, 8) == 3
  assert Common.numberToLineNumber(20, 8) == 3
  assert Common.numberToLineNumber(21, 8) == 3
  assert Common.numberToLineNumber(22, 8) == 3
  assert Common.numberToLineNumber(23, 8) == 3
  assert Common.numberToLineNumber(24, 8) == 3
  assert Common.numberToLineNumber(25, 8) == 4
  assert Common.numberToLineNumber(26, 8) == 4
  assert Common.numberToLineNumber(27, 8) == 4
  assert Common.numberToLineNumber(28, 8) == 4
  assert Common.numberToLineNumber(29, 8) == 4
  assert Common.numberToLineNumber(30, 8) == 4
  assert Common.numberToLineNumber(31, 8) == 4
  assert Common.numberToLineNumber(32, 8) == 4
  assert Common.numberToLineNumber(33, 8) == 5
  assert Common.numberToLineNumber(34, 8) == 5
  assert Common.numberToLineNumber(35, 8) == 5
  assert Common.numberToLineNumber(36, 8) == 5
  assert Common.numberToLineNumber(37, 8) == 5
  assert Common.numberToLineNumber(38, 8) == 5
  assert Common.numberToLineNumber(39, 8) == 5
  assert Common.numberToLineNumber(40, 8) == 5
  assert Common.numberToLineNumber(41, 8) == 6
  assert Common.numberToLineNumber(42, 8) == 6
  assert Common.numberToLineNumber(43, 8) == 6
  assert Common.numberToLineNumber(44, 8) == 6
  assert Common.numberToLineNumber(45, 8) == 6
  assert Common.numberToLineNumber(46, 8) == 6
  assert Common.numberToLineNumber(47, 8) == 6
  assert Common.numberToLineNumber(48, 8) == 6
  assert Common.numberToLineNumber(49, 8) == 7
  assert Common.numberToLineNumber(50, 8) == 7
  assert Common.numberToLineNumber(51, 8) == 7
  assert Common.numberToLineNumber(52, 8) == 7
  assert Common.numberToLineNumber(53, 8) == 7
  assert Common.numberToLineNumber(54, 8) == 7
  assert Common.numberToLineNumber(55, 8) == 7
  assert Common.numberToLineNumber(56, 8) == 7
  assert Common.numberToLineNumber(57, 8) == 8
  assert Common.numberToLineNumber(58, 8) == 8
  assert Common.numberToLineNumber(59, 8) == 8
  assert Common.numberToLineNumber(60, 8) == 8
  assert Common.numberToLineNumber(61, 8) == 8
  assert Common.numberToLineNumber(62, 8) == 8
  assert Common.numberToLineNumber(63, 8) == 8
  assert Common.numberToLineNumber(64, 8) == 8