BLACK = 0
BLACKNAME = 'Black'
WHITE = 1
WHITENAME = 'White'

MAX_ELEMENT = 8
DEFAULT = 'Default'

KING = 'King'
KINGVALUE = 4
KINGSHORT = 'K'
QUEEN = 'Queen'
QUEENVALUE = 9
QUEENSHORT = 'Q'
ROOK = 'Rook'
ROOKVALUE = 5
ROOKSHORT = 'R'
BISHOP = 'Bishop'
BISHOPVALUE = 3
BISHOPSHORT = 'B'
KNIGHT = 'Knight'
KNIGHTVALUE = 3
KNIGHTSHORT = 'N'
PAWN = 'Pawn'
PAWNVALUE = 1
PAWNSHORT = 'P'

KINGBLACKCODE = '	&#x265a;'
QUEENBLACKCODE = '&#9819;'
ROOKBLACKCODE = '&#9820;'
BISHOPBLACKCODE = '&#9821;'
KNIGHTBLACKCODE = '&#9822;'
PAWNBLACKCODE = '&#9823;'

KINGWHITECODE = '&#9812;'
QUEENWHITECODE = '&#9813;'
ROOKWHITECODE = '&#9814;'
BISHOPWHITECODE = '&#9815;'
KNIGHTWHITECODE = '&#9816;'
PAWNWHITECODE = '&#9817;'
